### ISSUE TITLE
Ability to search through existing commands and show chord to get there?

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/vscode-which-key#12]
Not sure if there's already a way to do this, but it'd be neat if there were some kind of UI to search for a command that is mapped via vscode-which-key and also display the chord for future reference. It's unfortunate that it can't show up in the default command palette itself, but beggars can't be choosers 🙂

**Comment by stevenguh** [comment]
That's an interesting idea. QuickPick API does allow adding buttons, maybe we can add a search button to search names and commands that it executes.

I thought about another approach which is a pure vs code command to create QuickPick instead of integrated into the menu. However, it gets hairy because this extension can consume by other extension. I will think more about each approach.

**Comment by stevenguh** [comment]
Just thought we probably should implement this as a command like `helm-descbinds` instead of a button in the UI so in the case of VSpaceCode, we can bind this command as `SPC ?`.

![image](https://user-images.githubusercontent.com/3455662/102048135-6b066480-3d93-11eb-8c97-a619af150324.png)

**Comment by MarcoIeni** [comment]
Wow, that would be great!

**Comment by stevenguh** [comment]
Released `v0.9.0` finally! Closing this :)
