### ISSUE TITLE
VSpaceCode is missing from the Open VSX registry

### ISSUE THREAD

**Issue by arnfaldur** [VSpaceCode/vscode-which-key#16]
Installing VSpaceCode is quite the hassle when using VSCodium, Theia, etc. as they don't use the microsoft marketplace.

Adding VSpaceCode to the registry would solve this and make it more widely available as well as making the community less dependent on Microsoft.

There is a guide to do it here.
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
I might do it myself when I have more time.

**Comment by MarcoIeni** [comment]
If you want to do it, it would be great! This should be integrated with the [GitHub Deploy Action](https://github.com/VSpaceCode/VSpaceCode/blob/master/.github/workflows/deploy.yml).
As an action to deploy the extension we are using [this one](https://github.com/lannonbr/vsce-action), but I don't see an option to update to the Open VSX registry, too.
The documentation you linked suggest another action. For me we can do the transition to that one if it is compatible with both.
Furthermore, this extension has no a "deploy" action like VSpaceCode, this might be a good time to add it.

Anyway, one of the maintainers has to setup the token, right?

Side note: this issue is good for both the vspacecode-which-key (this repo) and VSpaceCode extension.
We can keep the discussion here for both I think.

**Comment by stevenguh** [comment]
> Furthermore, this extension has no a "deploy" action like VSpaceCode, this might be a good time to add it.

I've been deploying manually. I will add an action and a token just like VSpaceCode for this repo tomorrow so it has deploy action to MS registry like VSpaceCode. We need more discussion in moving forward with open VSX, see below.

---

As far as supporting extra registry, I am supportive of it, and I hope it won't end up being supporting multiple registries due to possible fragmentations.

A tidbit about Open VSX: when I tried to register/log in, it requires a github account, and reading of the profile. There isn't a email option as far as I know. It seems like we are registering/giving access our our profile to TypeFox, a company in Germany. I am not sure if I personally want to register for it.

As far as deployment goes, there is an action that supports deploying to all registries https://github.com/HaaLeo/publish-vscode-extension. It seems to contain more code than the one we are using, probably need to take a look.

**Comment by stevenguh** [comment]
I added automatic deployment on vscode-which-key just like the one on VSpaceCode on https://github.com/VSpaceCode/vscode-which-key/commit/8104b93fe19086422333033b7a5ef09c6b6b022e

**Comment by bernardini687** [comment]
hi all! any updates here? i'd like to try VSpaceCode on vscodium :)
can't find that nor vscode-which-key on the marketplace!

**Comment by stevenguh** [comment]
Let's wait until they transition to Eclipse Foundation. https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management

**Comment by stevenguh** [comment]
Just an update. I signed up with my github account and claimed the `VSpaceCode` namespace. I also updated the github action, which means the next version will be deployed to both vs marketplace and open-vsx

@MarcoIeni I can add you in as another owner to the namespace in open-vsx as long as you signup with you github account. Let me know if you want to do that.

**Comment by MarcoIeni** [comment]
That's great Steven, thanks!

On which website should I sign in?

**Comment by stevenguh** [comment]
You can sign in with you github account on https://open-vsx.org

**Comment by MarcoIeni** [comment]
done

**Comment by stevenguh** [comment]
added :)

**Comment by stevenguh** [comment]
New version is released. https://open-vsx.org/extension/VSpaceCode/whichkey

**Comment by MarcoIeni** [comment]
Really happy that VSCodium users can use our extensions. Thanks again Steven :)
